/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Report5;

public class App {
    public static void main(String[] args) {
        String str = null;
        System.out.println(str.length());
    }
}
